### ISSUE TITLE
error compiling - std::min not a member of std

### ISSUE THREAD

**Issue by brucelane** [bakercp/ofxIO#16]
hello,
on this line:
https://github.com/bakercp/ofxIO/blob/develop/libs/ofxIO/src/ByteBuffer.cpp#L77 min is not a member of std

**Comment by bakercp** [comment]
compiler?  platform?

**Comment by brucelane** [comment]
visual studio 2015 on windows 10

**Comment by bakercp** [comment]
cause it definitely is.  perhaps it needs http://en.cppreference.com/w/cpp/algorithm/min

can you add 

```c++
#include <algorithm>
```

to https://github.com/bakercp/ofxIO/blob/develop/libs/ofxIO/src/ByteBuffer.cpp#L27

**Comment by brucelane** [comment]
yes it works with adding #include <algorithm> to ByteBuffer.h

**Comment by bakercp** [comment]
I'll fix it.

**Comment by brucelane** [comment]
thank you, this can be closed

**Comment by bakercp** [comment]
Can you check with the latest develop?

**Comment by brucelane** [comment]
I'm using the develop branch already

**Comment by bakercp** [comment]
I meant the updated one I just pushed a fix to. :)

**Comment by brucelane** [comment]
yes, fine!
