### ISSUE TITLE
#include "json.hpp"

### ISSUE THREAD

**Issue by undessens** [bakercp/ofxIO#20]
I am compiling ofxIO on raspberry, as a dependencie of a another addons. 
I got json.hpp include in ofxIO.h , "no such file or directory" . Where should i find it ?

**Comment by bakercp** [comment]
Hi -- 

The `stable` branch of this repository is meant to be compatible with the openFrameworks [stable branch](https://github.com/openframeworks/openFrameworks/tree/stable), which corresponds to the latest official openFrameworks release.

The `master` branch of this repository is meant to be compatible with the openFrameworks [master branch](https://github.com/openframeworks/openFrameworks/tree/master).

`json.hpp` was added in the openFrameworks master branch 0.10.+ and is included in `ofxIO` stable branch as a backport.

So, it sounds like you are using a stable release of openFrameworks, so you should be using the  use the ofxIO stable branch ... which includes json.hpp.

Make sense?

**Comment by moebiussurfing** [comment]
it worked for me downloading the ofxIO stable branch, for 0.9.8 in VS.
I used the addon to run the ofxSerial examples

**Comment by bakercp** [comment]
Please try the stable branch for release versions of openFrameworks and the master branch for the development version.  Closing for now, please reopen if that doesn't work.
