### ISSUE TITLE
fatal error: json.hpp: No such file or directory on the Pi with 0.98 tried stable and master branch

### ISSUE THREAD

**Issue by mhellar** [bakercp/ofxIO#21]
/home/pi/openFrameworks/addons/ofxIO/src/ofxIO.h:13:20: fatal error: json.hpp: No such file or directory
 #include "json.hpp"

On raspian pixel using of 0.9.8 and both stable and master branch of ofxIO

Thanks for any help!

**Comment by bakercp** [comment]
Please try the stable branch for release versions of openFrameworks and the master branch for the development version.  Closing for now, please reopen if that doesn't work.
