### ISSUE TITLE
linking errors when compiling in linuxarmv6l

### ISSUE THREAD

**Issue by hardjob** [bakercp/ofxIO#22]
I tried to compile an app that use ofxIO in raspberry pi 3 , but i got some linking errors related to Poco
i use the master branch of this plugin also master branch of Poco with OF master branch . i tried the same app on Ubuntu and it works fine ...

**Comment by bakercp** [comment]
What errors? What version of ofxIO, which example? Which version of Raspbian? How did you install OF master branch, etc etc.

**Comment by hardjob** [comment]
here are some errors
```
/home/pi/OF/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/ByteBufferUtils.o: In function `ofx::IO::ByteBufferUtils::copyStreamToBuffer(std::istream&, ofx::IO::ByteBuffer&, unsigned int)':
ByteBufferUtils.cpp:(.text+0x198): undefined reference to `Poco::Bugcheck::assertion(char const*, char const*, int, char const*)'
/home/pi/OF/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/ByteBufferUtils.o: In function `ofx::IO::ByteBufferUtils::loadFromFile(std::string const&, ofx::IO::ByteBuffer&, bool, std::_Ios_Openmode)':
ByteBufferUtils.cpp:(.text+0x3f0): undefined reference to `Poco::FileInputStream::FileInputStream(std::string const&, std::_Ios_Openmode)'
ByteBufferUtils.cpp:(.text+0x448): undefined reference to `Poco::FileIOS::close()'
ByteBufferUtils.cpp:(.text+0x450): undefined reference to `Poco::FileInputStream::~FileInputStream()'
ByteBufferUtils.cpp:(.text+0x548): undefined reference to `Poco::IOException::IOException(std::string const&, int)'
ByteBufferUtils.cpp:(.text+0x578): undefined reference to `Poco::FileInputStream::~FileInputStream()'
ByteBufferUtils.cpp:(.text+0x60c): undefined reference to `typeinfo for Poco::IOException'
ByteBufferUtils.cpp:(.text+0x610): undefined reference to `Poco::IOException::~IOException()'
/home/pi/OF/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/ByteBufferUtils.o: In function `ofx::IO::ByteBufferUtils::saveToFile(ofx::IO::ByteBuffer const&, std::string const&, std::_Ios_Openmode)':
ByteBufferUtils.cpp:(.text+0x65c): undefined reference to `Poco::FileOutputStream::FileOutputStream(std::string const&, std::_Ios_Openmode)'
ByteBufferUtils.cpp:(.text+0x6a4): undefined reference to `Poco::FileIOS::close()'

```

i use OF master version , also the master branch of ofxIO
OS version : Raspbian 8.0 (jessie)
i create the app under apps/devApps, and placed the addons needed , then run make to compile it

**Comment by bakercp** [comment]
Did you install the pre-compiled libraries (it must be done manually if you cloned master).  See these instructions ...

https://github.com/openframeworks/openFrameworks/blob/master/INSTALL_FROM_GITHUB.md#download-dependencies

**Comment by hardjob** [comment]
yes i executed all scripts mentioned , to install dependencies and compileOF ..

**Comment by bakercp** [comment]
Which ofxIO example are you trying to compile?

**Comment by hardjob** [comment]
it's an app i created in order to take an image and save it to server with http post request
here is the app attached
[img_to_server.tar.gz](https://github.com/bakercp/ofxIO/files/1012534/img_to_server.tar.gz)

**Comment by bakercp** [comment]
When you installed the libraries, did you explicitly install the armv6 libs:

e.g.

```
scripts/linux/download_libs.sh -a armv6l
```

If not, you probably downloaded the armv7l libs, since RPI3 is armv7l, yet we compile for armv6l for backward compatibility.

**Comment by bakercp** [comment]
Or these steps ...

```
cd openFrameworks/scripts/linux/debian
sudo ./install_dependencies.sh
cd ..
./download_libs.sh --platform linuxarmv6l
./compileOF.sh
```

**Comment by hardjob** [comment]
Thank you 
it works

**Comment by bakercp** [comment]
Cool. I made a PR in OF as you aren't the first person to have this issue. 

https://github.com/openframeworks/openFrameworks/issues/5616

Good luck with the project!
