### ISSUE TITLE
segmentation fault on archlinux

### ISSUE THREAD

**Issue by icq4ever** [bakercp/ofxIO#26]
hello. first thank you so much for this great addon.

compile without any error. but when run, throw segmentation fault.

```sh
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal libcurl glfw3 rtaudio libpulse-simple alsa gl glu glew gtk+-3.0 libmpg123 
with PKG_CONFIG_LIBDIR=
/bin/sh: line 1: 28559 Segmentation fault      (core dumped) ./example_compression
make: *** [/home/icq4ever/oF/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:197: RunRelease] Error 139

```

but it's working well on raspberry pi (stretch)

**Comment by icq4ever** [comment]
it's stable branch. here is the debug logs.
crash in master branch as well. but not debuging yet.

![ofxio_debug](https://user-images.githubusercontent.com/530796/54027392-ba922680-41e4-11e9-91aa-fec136bbae36.png)

**Comment by icq4ever** [comment]
opend  [oF forum thread](https://forum.openframeworks.cc/t/segfault-with-example-from-ofxio-addon/31945)

**Comment by icq4ever** [comment]
it's not related with `ofxIO`. but `ofxPoco`
as a suggestion from [here](https://forum.openframeworks.cc/t/using-ofxpoco-results-into-segmentation-fault/30214/4?u=icq4ever), runtime error fixed. 

I'll close issue. 
thanks.

**Comment by bakercp** [comment]
Glad you figured it out.  It is usually a Poco issue because ofxIO uses Poco pretty heavily.

**Comment by icq4ever** [comment]
thank you for reply @bakercp  :)
