### ISSUE TITLE
how to check folder outside of ofToDataPath()

### ISSUE THREAD

**Issue by stephanschulz** [bakercp/ofxIO#28]
Any string path I am passing in to the function becomes a path assumed to be inside ofToDataPath().
I can see you are adding ofToDataPath();
here:
https://github.com/bakercp/ofxIO/blob/master/libs/ofxIO/src/DirectoryUtils.cpp#L124

How can I get folder content listed in any system folder?
I am using this call:
```
  ofxIO::DirectoryUtils::list(_path, files, true, &pathFilter, false);
```

Unfortunately I do not know how to construct a `const Poco::File& directory`, which seems an other void DirectoryUtils::list() alternative.

**Comment by bakercp** [comment]
The line you cited actually turns any string into an absolute path -- you should just be able to pass an absolute file path to that function (start it with a forward slash on *nix) systems.

**Comment by stephanschulz** [comment]
[notice ] _path Macintosh HD⁩/Users⁩/stephanschulz⁩/Dropbox⁩/temp⁩/⁨sounds_rec_box⁩
[ error ] DirectoryUtils::list: "/Applications/of_v0.10.1_osx_release/apps/BorderTuner/NDI-mic-sender/bin/data/Macintosh HD⁩/Users⁩/stephanschulz⁩/Dropbox⁩/temp⁩/⁨sounds_rec_box⁩" not found

I am setting:
```
string localCuratedFolder = "/Macintosh HD⁩/Users⁩/stephanschulz⁩/Dropbox⁩/temp⁩/⁨sounds_rec_box⁩";
ofxIO::DirectoryUtils::list(localCuratedFolder, files, true, &pathFilter, false);
```
but get
```
[ error ] DirectoryUtils::list: "/Macintosh HD⁩/Users⁩/stephanschulz⁩/Dropbox⁩/temp⁩/⁨sounds_rec_box⁩" not found.
```
???

**Comment by stephanschulz** [comment]
neither this works:

```
string localCuratedFolder = userPath.getUserHomeDir()+"/Desktop/⁨sounds_rec_box/";
ofxIO::DirectoryUtils::list(localCuratedFolder, files, true, &pathFilter, false);
```
```
[ error ] DirectoryUtils::list: "/Users/stephanschulz/Desktop/⁨sounds_rec_box/" not found.
```

**Comment by bakercp** [comment]
hmm ... odd ... on the command line if you run 
```
ls -la "/Macintosh HD⁩/Users⁩/stephanschulz⁩/Dropbox⁩/temp⁩/⁨sounds_rec_box⁩"
```

Does it list the contents of that directory?

**Comment by bakercp** [comment]
Or just run 

```
ls -la "/Users⁩/stephanschulz⁩/Dropbox⁩/temp⁩/⁨sounds_rec_box⁩"
```

as usually the HD name is not on mac path.

**Comment by stephanschulz** [comment]
good idea. 
also does not work.
so it must be some other problem.
```
ls: /Users⁩/stephanschulz⁩/Dropbox⁩/temp⁩/⁨sounds_rec_box⁩: No such file or directory
MacBook-Pro:~ stephanschulz$ 
```
<img width="264" alt="Screen Shot 2019-10-29 at 5 18 48 PM" src="https://user-images.githubusercontent.com/1054816/67810031-31c84380-fa70-11e9-9913-f65b56a82296.png">

**Comment by stephanschulz** [comment]
correction.
```
ls -la /Users/stephanschulz/Dropbox/temp/sounds_rec_box
```
works without the quotation marks.

**Comment by bakercp** [comment]
```
std::string localCuratedFolder = "/Users/stephanschulz/Dropbox/temp/sounds_rec_box⁩";

ofxIO::DirectoryUtils::list(localCuratedFolder, files, true, &pathFilter, false);

```

theoretically that should work then ...

**Comment by stephanschulz** [comment]
so strange.
I even went and used your example_directory_list 
and still have those problems.
but running the same thing in the terminal works.
I am on macOS 10.14.3 Mojave. Might it be related to that?
```
2019-10-29 17:30:20.751265-0400 example_directory_listDebug[1407:16195] MessageTracer: Falling back to default whitelist
[ error ] DirectoryUtils::list: "/Users/stephanschulz/Dropbox/temp/sounds_rec_box⁩" not found.
```

but using your add-on with ofToDataPath("sounds_curated") works just fine.
```
[notice ] _path ../../../data/sounds_curated
```

**Comment by bakercp** [comment]
It's too weird and must be a code bug.  Can you try this:

```c++
std::filesystem::path path("/Users/stephanschulz/Dropbox/temp/sounds_rec_box⁩");

if (std::filesystem::exists(path))
{
	std::cout << path << " exists!" << std::endl;
}
else
{
	std::cout << path << " does not exists!" << std::endl;
}

if (std::filesystem::is_directory(path))
{
	std::cout << path << " is a directory!" << std::endl;
}
else
{
	std::cout << path << " is NOT a directory!" << std::endl;
}
```

**Comment by stephanschulz** [comment]
<img width="897" alt="Screen Shot 2019-10-29 at 5 46 28 PM" src="https://user-images.githubusercontent.com/1054816/67811860-17906480-fa74-11e9-89f5-ce8cb21a7972.png">

I also tired to use your latest version but got some other compile errors, so I went back to my version from April

**Comment by bakercp** [comment]
hm ... if `std::filsystem::path` can't see the directory, then I believe it may be something odd with your computer setup.  If you just use partial paths incrementally, what happens?

i.e.

See if this exists ..
```
std::filesystem::path path("/");
```
then 
```
std::filesystem::path path("/Users/");
```

then 
```
std::filesystem::path path("/Users/stephanschulz");
```

etc ...

**Comment by stephanschulz** [comment]
maybe the underscore in the filename is the cause for all this.

```
"/" exists!
"/" is a directory!
"/Users/" exists!
"/Users/" is a directory!
"/Users/stephanschulz/" exists!
"/Users/stephanschulz/" is a directory!
"/Users/stephanschulz/Dropbox/temp" exists!
"/Users/stephanschulz/Dropbox/temp" is a directory!
"/Users/stephanschulz/Dropbox/temp/sounds_rec_box⁩" does not exists!
"/Users/stephanschulz/Dropbox/temp/sounds_rec_box⁩" is NOT a directory!
"/Users/stephanschulz/Dropbox/temp/soundsABC/" exists!
"/Users/stephanschulz/Dropbox/temp/soundsABC/" is a directory!
"/Users/stephanschulz/Dropbox/temp/soundsRecBox/" exists!
"/Users/stephanschulz/Dropbox/temp/soundsRecBox/" is a directory!
```

By the way. Thank you very much for all your responses.

**Comment by bakercp** [comment]
It very well could be but that is pretty odd.  My only guess is that maybe somehow it's a different Unicode underscore or something?  Because as far as I know, regular underscores are totally legal in paths ... if you cut go to the directory in the terminal and then type

```
pwd
```

and cut the path and paste it into Xcode editor, does it work?

**Comment by stephanschulz** [comment]
yes using this path (which looks identical) works.

```
    testPath("/Users/stephanschulz/Dropbox/temp/sounds_rec_box⁩");
    testPath("/Users/stephanschulz/Dropbox/temp/sounds_rec_box");  
```

console 
```
"/Users/stephanschulz/Dropbox/temp/sounds_rec_box⁩" does not exists!
"/Users/stephanschulz/Dropbox/temp/sounds_rec_box⁩" is NOT a directory!
"/Users/stephanschulz/Dropbox/temp/sounds_rec_box" exists!
"/Users/stephanschulz/Dropbox/temp/sounds_rec_box" is a directory!
```

in any case. it works now by either renaming the folder or copying the path via pwd.
maybe the underscore has a different unicode as you mentioned.

**Comment by bakercp** [comment]
`sounds_rec_box⁩`
... looks like this in hex:
<img width="807" alt="a_txt" src="https://user-images.githubusercontent.com/300484/67824038-d788ac00-fa8a-11e9-9ad5-7eb6135da451.png">

`sounds_rec_box`
... looks like this in hex:<img width="807" alt="b_txt" src="https://user-images.githubusercontent.com/300484/67824062-ed966c80-fa8a-11e9-8c7e-cc670abcd8e1.png">

By some magic, the first one has this invisible Unicode character at the end https://unicode-table.com/en/2069/.  The second one does not.

**Comment by stephanschulz** [comment]
so strange.
I will add it to my long term memory in case it ever happens again.
thank you for your help.

**Comment by bakercp** [comment]
I actually have had it happen before.  On occasion, the right combination of keys on a mac will insert special characters. I've also had it happen when using a different keyboard layout / input.  It's a really obnoxious bug that is difficult to track down.  Closing this for now.
